name: ClickUp task creation

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: node scripts/create-task.js
      with:
        # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issues
        ISSUE_ID: '${{ github.event.issue.number }}'
        ISSUE_TITLE: '${{ github.event.issue.title }}'
        ISSUE_URL: '${{ github.event.issue.url }}'
        ISSUE_DESCRIPTION: '${{ github.event.issue.body }}'
        CLICKUP_API_KEY: '${{ secrets.CLICKUP_API_KEY }}'
        CLICKUP_LIST_ID: '${{ secrets.CLICKUP_LIST_ID }}'